#!/bin/bash

echo "Starting new build."\
 &&\
 RUST_TARGET_PATH="$PWD"\
 RUST_BACKTRACE=1\
 xargo build --bin libnxbin --target=aarch64-none-elf \
 &&\
 echo "Compiled rust target. Now creating nro."\
 &&\
 elf2nro target/aarch64-none-elf/release/libnxbin.nx_elf libnxbin.nro\
 &&\
 echo "Finished making nro."
